- package.json
- pages/rebranding-rationale.tsx
- pages/registration.tsx
- yarn.lock
- Added tailwind prettier plugin
- Scaffolded registration page
> registration

- components/RegistrationErrorMsg.tsx
- components/RegistrationSuccessMsg.tsx
- pages/_app.tsx
- pages/rebranding-rationale.tsx
- pages/registration.tsx
- Set up userbase in registration page
- Added basic registration functionality
> more registration

- components/JoinDiscordButton.tsx
- components/Navbar.tsx
Cute Join Discord button
Follows #24 
Closes #26
> Create discord button component

- pages/index.tsx
Remove property of height: 100vh making an unnecessary scrollbar appear
> Fix vertical scroll

- components/Navbar.tsx
- public/neovimconf-logo.svg
Logo is available in /public/neovimconf-logo.svg now
Removed background colour of navbar to increase the visibility of logo.
> Add logo to navbar

- components/Navbar.tsx
- scroll to top on clicking logo if on home page
- on clicking logo navigate to home if on other pages
- closes #40
> Improve Navbar logo behaviour

- pages/index.tsx
- public/neovimconf-logo.svg
- remove onClick event handler to scroll to top
- remove cursor pointer
- hero section will be the top section so don't need to scroll to top on clicking the logo
> Add logo to hero

- components/JoinDiscordButton.tsx
- components/Navbar.tsx
- package-lock.json
- package.json
- pages/index.tsx
- yarn.lock
- style changes to button
- Some style changes to buttons
> hover states 2

- pages/code-of-conduct.tsx
- styles/main.css
- yarn.lock
Partial text for Code Of Conduct will submit the rest tomorrow.
> Add the code of conduct page

- pages/rebranding-rationale.tsx
> Fix overlap of navbar and rebranding main section

- components/Navbar.tsx
- keep background colour same as body background colour
- add shadow on scroll
> Add drop shadow to navbar on scroll

- pages/code-of-conduct.tsx
Based on:
https://github.com/vim-conf-live/vim-conf-live-2021/blob/main/pages/code-of-conduct.vue
> Update CoC to match 2021's

- pages/code-of-conduct.tsx
add the layout to the code of conduct page
> Add layout codeofconduct page

- pages/code-of-conduct.tsx
- styles/main.css
> Add style improvements to the code of conduct page

- components/Navbar.tsx
- pages/code-of-conduct.tsx
- styles/main.css
Now the active link is marked greenyellow  😄 🟢
> Navigation bar improvements

- pages/index.tsx
Changed color, size of text and added sign up emoji.
> Update Speaker Sign Up button

- styles/main.css
A little hardcoded but it works!
Updated the size of the YT videos in multiple resolutions to ensure that it's always centered with a 16:9 aspect ratio. I tested from 360px to 1920px width.
> Fix youtube aspect ratios

- components/LogoSection.tsx
- components/PastVideos.tsx
- package-lock.json
- pages/index.tsx
- pages/registration.tsx
- styles/main.css
- utils/registerToConf.ts
Refactor in PastVideos.tsx and LogoSection.tsx
> Chore Logo Section Refactor & Add Registration Link

- hooks/useVimMappings.tsx
- pages/_app.tsx
- pages/index.tsx
Scroll up and down with J and K, go to top and bottom with g and G
Based on: https://devtrium.com/posts/how-keyboard-shortcut
> Vim mappings for navigation

- public/robots.txt
> Update robots.txt to index homepage

- components/MCSection.tsx
- components/SpeakersSection.tsx
- pages/index.tsx
This is just the section itself the contents will come later today.
Don't merge until then please.
> Add a master of ceremonies section

- components/Card.tsx
- components/SpeakersSection.tsx
> Add mastodon social

- components/Card.tsx
- components/SpeakersSection.tsx
- package.json
- tailwind.config.js
- yarn.lock
- increase the number of cards in speaker section to three
- remove "Read more" button
- add expand button
> Fix speaker cards

- components/Card.tsx
New pull request due to previous one having merge conflicts
> Fix card image aspect ratio

- components/Countdown.tsx
- tailwind.config.js
the button links to ThePrimeagen profile on youtube and twitch.
> Add twitch and youtube button when countdown finishes
